MSVC can't handle constexpr INVALID_HANDLE_VALUE
Causes error C2131: expression did not evaluate to a constant
note: failure was caused by unevaluable pointer value